import type { z } from 'zod'
import { SelectorSchema, StepSchema, VerbSchema } from './planschema'
import { ConditionSchema } from './schema'
import { GUARDS, PERMISSIONS, verbName } from './verbs'

// The reference of the plan language (M8.3; review, "De editor"): the fields
// of a step, the conditions, the verbs with who may use them, the selectors
// and the bindings, read from the schemas and the permission table. One
// source for the editor and for the part of CHRONICLER.md between the
// reference markers (npm run reference writes it; a test keeps it in step).

export const REFERENCE_START = '<!-- reference: generated by npm run reference, do not edit by hand -->'
export const REFERENCE_END = '<!-- end of reference -->'

type Def = {
  type: string
  innerType?: z.ZodType
  defaultValue?: unknown
  options?: z.ZodType[]
  element?: z.ZodType
  items?: z.ZodType[]
  entries?: Record<string, string>
  values?: unknown[]
  valueType?: z.ZodType
  shape?: Record<string, z.ZodType>
  getter?: () => z.ZodType
}

const defOf = (s: z.ZodType): Def => (s as unknown as { def: Def }).def

/** A field's type in plain words. */
function typeOf(s: z.ZodType): string {
  if (s === ConditionSchema) return 'condition'
  if (s === SelectorSchema) return 'selector'
  const d = defOf(s)
  switch (d.type) {
    case 'string':
      return 'text'
    case 'number':
      return 'number'
    case 'boolean':
      return 'true/false'
    case 'optional':
    case 'default':
      return typeOf(d.innerType!)
    case 'union':
      return [...new Set(d.options!.map(typeOf))].join(' or ')
    case 'array':
      return `list of ${typeOf(d.element!)}`
    case 'tuple':
      return `[${d.items!.map(typeOf).join(', ')}]`
    case 'enum':
      return Object.values(d.entries!).join(' | ')
    case 'literal':
      return d.values!.map(String).join(' | ')
    case 'record':
      return `{ key: ${typeOf(d.valueType!)} }`
    case 'object':
      return `{ ${fieldsOf(s).join(', ')} }`
    default:
      return d.type
  }
}

/** The fields of an object: name, type, and ? when it may be left out (with its default). */
function fieldsOf(s: z.ZodType): string[] {
  return Object.entries(defOf(s).shape ?? {}).map(([name, f]) => {
    const d = defOf(f)
    const optional = d.type === 'optional' || d.type === 'default'
    const fallback = d.type === 'default' ? ` = ${JSON.stringify(d.defaultValue)}` : ''
    return `${name}${optional ? '?' : ''}: ${typeOf(f)}${fallback}`
  })
}

/** The objects of a union, with the unions inside it flattened. */
function optionsOf(s: z.ZodType): z.ZodType[] {
  const d = defOf(s)
  if (d.type === 'lazy') return optionsOf(d.getter!())
  if (d.type === 'union') return d.options!.flatMap(optionsOf)
  return [s]
}

const describe = (s: z.ZodType): string => (s as unknown as { description?: string }).description ?? ''

export interface ReferenceEntry {
  name: string
  form: string
  text: string
  /** For verbs: who may use it besides fixed content. */
  who?: { rules: boolean; brain: boolean; chronicler: boolean }
}

export interface Reference {
  step: ReferenceEntry[]
  conditions: ReferenceEntry[]
  verbs: ReferenceEntry[]
  selectors: ReferenceEntry[]
  bindings: ReferenceEntry[]
}

/** The bindings a plan of the aftermath or an intention starts with (aftermath.ts, npc/intentions.ts). */
const BINDINGS: [string, string][] = [
  ['$a, $b, $c', 'the people the signal is about, in order; for an intention, $a is the one who chose it'],
  ['$who', 'the first of them; in a step with each, the member it is done for'],
  ['$place', 'where it happened'],
  ['$area', 'the area of that place'],
  ['$signal', 'the signal itself'],
  ['$subject, $key, $value', 'the claim of the fact that raised the signal'],
  ['$at', 'for a claim about a service (loc_x#taproom), the place it is at'],
]

export function languageReference(): Reference {
  const entry = (s: z.ZodType, name: string, text: string): ReferenceEntry => ({ name, form: `{ ${fieldsOf(s).join(', ')} }`, text })
  return {
    step: Object.entries(defOf(StepSchema).shape!).map(([name, f]) => ({ name, form: name === 'do' ? 'a verb' : typeOf(f), text: describe(f) })),
    conditions: optionsOf(ConditionSchema).map((s) => entry(s, Object.keys(defOf(s).shape!)[0]!, describe(s))),
    verbs: optionsOf(VerbSchema).map((s) => {
      const name = verbName(Object.fromEntries(Object.keys(defOf(s).shape!).map((k) => [k, 1])) as never)
      const p = PERMISSIONS[name]
      const guard = GUARDS[name]
      const text = p ? `${p.text.charAt(0).toUpperCase()}${p.text.slice(1)}.${guard ? ` Standard conditions: ${guard}.` : ''}` : ''
      return { ...entry(s, name, text), ...(p ? { who: { rules: p.rules, brain: p.brain, chronicler: p.chronicler } } : {}) }
    }),
    selectors: optionsOf(SelectorSchema).map((s) => (defOf(s).type === 'object' ? entry(s, Object.keys(defOf(s).shape!)[0]!, describe(s)) : { name: 'id', form: 'text', text: describe(s) })),
    bindings: BINDINGS.map(([name, text]) => ({ name, form: '', text })),
  }
}

/** The reference as Markdown, for CHRONICLER.md. */
export function referenceMarkdown(): string {
  const r = languageReference()
  const who = (e: ReferenceEntry) => (e.who ? ` Rules ${e.who.rules ? 'yes' : 'no'}, brain ${e.who.brain ? 'yes' : 'no'}, chronicler ${e.who.chronicler ? 'yes' : 'no'}.` : '')
  const list = (entries: ReferenceEntry[], withForm = true) => entries.map((e) => `- \`${e.name}\`${withForm && e.form ? ` \`${e.form}\`` : ''}: ${e.text}${who(e)}`)
  return [
    REFERENCE_START,
    '',
    '## Reference: the plan language',
    '',
    'Watchers, the standard aftermath, intentions, fixed plans, quests and your own plans all speak this language. A plan is steps; each step has a moment, conditions and one verb. In the builder all of it may be used; in your own plans during a game, only the verbs marked "chronicler yes".',
    '',
    '### A step',
    '',
    ...list(r.step),
    '',
    '### Conditions',
    '',
    ...list(r.conditions),
    '',
    '### Verbs',
    '',
    ...list(r.verbs),
    '',
    '### Selectors',
    '',
    'Where a verb wants someone or somewhere, it takes a selector.',
    '',
    ...list(r.selectors),
    '',
    '### Bindings',
    '',
    ...list(r.bindings, false),
    '',
    REFERENCE_END,
  ].join('\n')
}

/** The instruction without the reference: a run of the chronicler has its own list of verbs, only the builder needs it all. */
export function withoutReference(text: string): string {
  const start = text.indexOf(REFERENCE_START)
  const end = text.indexOf(REFERENCE_END)
  return start < 0 || end < start ? text : `${text.slice(0, start).trimEnd()}\n${text.slice(end + REFERENCE_END.length)}`
}

/** Sections of the working instruction for the world builder only (M10.27): where content lives, ids, the pieces, sparring. */
const BUILDER_SECTIONS = ['Where everything lives', 'Ids', 'The pieces', 'Sparring in the editor']

/**
 * The working instruction for a round in the game (M10.27: the night round
 * read 14,000 characters of it every night): without its reference part and
 * without the sections only the world builder needs. What the world adds
 * under its own headings stays whole.
 */
export function playGuide(text: string): string {
  return withoutReference(text)
    .split(/\n(?=## )/)
    .filter((part) => !BUILDER_SECTIONS.some((heading) => part.startsWith(`## ${heading}\n`)))
    .join('\n')
}

/** CHRONICLER.md with its reference part written anew (appended at the end the first time). */
export function withReference(text: string): string {
  const start = text.indexOf(REFERENCE_START)
  const end = text.indexOf(REFERENCE_END)
  if (start < 0 || end < start) return `${text.trimEnd()}\n\n${referenceMarkdown()}\n`
  return `${text.slice(0, start)}${referenceMarkdown()}${text.slice(end + REFERENCE_END.length)}`
}
