// Generated by npm run coverage from tests/fixtures/model: do not edit by hand.
// The tokens of the latest real reply of each kind of call, for the guide price per hour (M10.21).

export interface Measured {
  inputTokens: number
  outputTokens: number
  model: string
  date: string
}

export const MEASURED: Record<string, Measured> = {
  builder_draft: { inputTokens: 19676, outputTokens: 2288, model: 'claude-opus-5-5', date: '2026-09-29' },
  chat_line: { inputTokens: 977, outputTokens: 35, model: 'claude-sonnet-5', date: '2026-09-29' },
  chronicle: { inputTokens: 12032, outputTokens: 2243, model: 'claude-opus-5-5', date: '2026-09-29' },
  district: { inputTokens: 3137, outputTokens: 3071, model: 'claude-opus-5-5', date: '2026-09-29' },
  expansion: { inputTokens: 7490, outputTokens: 1249, model: 'claude-opus-5-5', date: '2026-09-29' },
  far_place: { inputTokens: 1956, outputTokens: 820, model: 'claude-opus-5-5', date: '2026-09-29' },
  improvise: { inputTokens: 1338, outputTokens: 121, model: 'claude-haiku-4-5-20251001', date: '2026-09-29' },
  journey: { inputTokens: 1001, outputTokens: 67, model: 'claude-opus-5-5', date: '2026-09-29' },
  land: { inputTokens: 6579, outputTokens: 1267, model: 'claude-opus-5-5', date: '2026-09-29' },
  legends: { inputTokens: 1310, outputTokens: 439, model: 'claude-opus-5-5', date: '2026-09-29' },
  lore_check: { inputTokens: 727, outputTokens: 40, model: 'claude-sonnet-5', date: '2026-09-29' },
  model_advice: { inputTokens: 3389, outputTokens: 584, model: 'claude-sonnet-5', date: '2026-09-29' },
  npc_goals: { inputTokens: 2850, outputTokens: 264, model: 'claude-sonnet-5', date: '2026-09-29' },
  npc_reply: { inputTokens: 3481, outputTokens: 244, model: 'claude-haiku-4-5-20251001', date: '2026-09-29' },
  outline: { inputTokens: 8056, outputTokens: 1512, model: 'claude-opus-5-5', date: '2026-09-29' },
  palette_draft: { inputTokens: 16837, outputTokens: 3633, model: 'claude-opus-5-5', date: '2026-09-29' },
  party_reply: { inputTokens: 1071, outputTokens: 84, model: 'claude-haiku-4-5-20251001', date: '2026-09-29' },
  test_call: { inputTokens: 540, outputTokens: 9, model: 'claude-opus-5-5', date: '2026-09-29' },
  tides: { inputTokens: 1195, outputTokens: 254, model: 'claude-opus-5-5', date: '2026-09-29' },
  voice_draft: { inputTokens: 14130, outputTokens: 2122, model: 'claude-opus-5-5', date: '2026-09-29' },
  weave: { inputTokens: 2404, outputTokens: 668, model: 'claude-opus-5-5', date: '2026-09-29' },
  world_enhance: { inputTokens: 23333, outputTokens: 933, model: 'claude-opus-5-5', date: '2026-09-29' },
  world_polish: { inputTokens: 17109, outputTokens: 1837, model: 'claude-sonnet-5', date: '2026-09-29' },
}
