// The engine is headless: no Electron, React or Node imports in this folder.
// It runs in the Electron main process, in the terminal (npm run play),
// in tests, and in the browser preview.

export * from './clock'
export * from './commands'
export * from './content'
export * from './worlds'
export * from './engine'
export * from './items'
export * from './parser'
export * from './rng'
export * from './state'
export * from './world'
export { Planner, isFailure } from './npc/planner'
export * from './dialogue/acts'
export * from './dialogue/checks'
export { timeGreeting } from './dialogue/fallback'
export { Dialogue, QUICK_OPTIONS } from './dialogue/conversation'
export * from './dialogue/guard'
export * from './dialogue/knowledge'
export * from './dialogue/llm'
export * from './dialogue/mock'
export * from './dialogue/prompt'
export * from './dialogue/relations'
export * from './dialogue/schema'
export * from './dialogue/topics'
export * from './dialogue/testset'
export { advance } from './simulation'
export * from './stories'
export * from './news'
export * from './journal'
export * from './chronicle'
export * from './people'
export * from './life'
export * from './pictures'
export * from './chronicler'
export * from './storylines'
export * from './requests'
export * from './npc/goals'
export * from './builder'
export { ATTRIBUTES, SAVES, RulesSchema, CreatureSchema, EncounterSchema, type Attribute, type Save, type Rules, type ClassDef, type Ancestry, type Background, type Patron, type Talent, type Creature, type Encounter, type Effect, type Ability, type Bonus } from './rules/schema'
export * from './rules/character'
export { character as playerCharacter, READY_MADE, sheetLines, type Clock } from './rules/player'
export * from './combat/types'
export { fightView, FIGHT_HELP } from './combat/flow'
export { balanceReport, marginProblems, MARGINS, standardGroups, characterAt, simulateFight, foeXp } from './combat/balance'

export * from './edit'
export * from './editor'
export * from './playtest'
