import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { MODEL_KINDS, type ModelKind } from '../src/engine/modelkinds'

// docs/COVERAGE.md (M10.20): per kind of model call, whether a test answers it
// with the mock model, which real replies are recorded as fixtures (with date
// and model), and when the last real trial ran. Made by npm run coverage; a
// test checks that the file is what this writes, and that the code makes no
// kind of call without a row.

export interface CoverageRow extends ModelKind {
  /** Test files that make this kind of call with the mock model or play its recorded replies. */
  tests: string[]
  /** Recorded real replies: date and model, newest first. */
  recorded: { date: string; model: string; where: string }[]
}

/** The kinds of call the code makes: every `schemaName: '...'` under src. */
export function kindsInCode(root: string): string[] {
  const found = new Set<string>()
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name)
      if (entry.isDirectory()) walk(path)
      else if (/\.tsx?$/.test(entry.name)) for (const m of readFileSync(path, 'utf8').matchAll(/schemaName: '([a-z_]+)'/g)) found.add(m[1]!)
    }
  }
  walk(join(root, 'src'))
  return [...found].sort()
}

type Recording = { kind?: string; step?: string; model?: string; date?: string }

function recordings(root: string): { kind: string; date: string; model: string; where: string }[] {
  const out: { kind: string; date: string; model: string; where: string }[] = []
  const models = join(root, 'tests/fixtures/model')
  if (existsSync(models)) {
    for (const kind of readdirSync(models)) {
      for (const file of readdirSync(join(models, kind)).filter((f) => f.endsWith('.json'))) {
        const r = JSON.parse(readFileSync(join(models, kind, file), 'utf8')) as Recording
        if (r.date && r.model) out.push({ kind, date: r.date, model: r.model, where: `tests/fixtures/model/${kind}/${file}` })
      }
    }
  }
  const builds = join(root, 'tests/fixtures/worldbuild')
  if (existsSync(builds)) {
    for (const build of readdirSync(builds)) {
      const steps = readdirSync(join(builds, build)).filter((f) => /^\d\d-.*\.json$/.test(f))
      const read = steps.map((f) => JSON.parse(readFileSync(join(builds, build, f), 'utf8')) as Recording)
      const dates = [...new Set(read.map((r) => r.date).filter(Boolean))].sort()
      const models = [...new Set(read.map((r) => r.model).filter(Boolean))].sort()
      if (dates.length) out.push({ kind: 'world_step', date: dates.at(-1)!, model: models.join(', '), where: `tests/fixtures/worldbuild/${build} (${steps.length} steps)` })
    }
  }
  return out.sort((a, b) => b.date.localeCompare(a.date))
}

export function coverage(root: string): { rows: CoverageRow[]; unlisted: string[]; stale: string[] } {
  const tests = readdirSync(join(root, 'tests')).filter((f) => f.endsWith('.test.ts')).sort()
  const texts = new Map(tests.map((f) => [f, readFileSync(join(root, 'tests', f), 'utf8')]))
  const recorded = recordings(root)
  const rows = MODEL_KINDS.map((k) => ({
    ...k,
    // A test that names the kind: the coverage test plays every kind; others make it through the game.
    tests: tests.filter((f) => texts.get(f)!.includes(`'${k.kind}'`) || texts.get(f)!.includes(`"${k.kind}"`)).map((f) => `tests/${f}`),
    recorded: recorded.filter((r) => r.kind === k.kind).map(({ date, model, where }) => ({ date, model, where })),
  }))
  const code = kindsInCode(root)
  return { rows, unlisted: code.filter((c) => !MODEL_KINDS.some((k) => k.kind === c)), stale: MODEL_KINDS.filter((k) => !code.includes(k.kind)).map((k) => k.kind) }
}

export function coverageMarkdown(rows: CoverageRow[]): string {
  const lines = [
    '# Coverage of the model calls',
    '',
    'Generated by `npm run coverage` from `src/engine/modelkinds.ts`, the tests and the recorded replies; do not edit by hand.',
    '',
    'Every kind of model call the game makes, whether a test answers it with the mock model, and which replies of a real model are recorded as fixtures. A real trial runs in the app with the key and models of the player, never in CI: `npm run trial -- --kind <kind>` (after `npm run build`) plays a fixed situation, checks the reply with the same readers and guard as the game, and with `--record` keeps it under `tests/fixtures/model/<kind>/`. The world build records a whole designer\'s document under `tests/fixtures/worldbuild/<build>/`, and `tests/m1020fixtures.test.ts` plays it again.',
    '',
    `${rows.length} kinds; ${rows.filter((r) => r.recorded.length).length} with a recorded real reply.`,
    '',
    '| Kind | Role | When | What it is for | Mock test | Recorded real replies | Last real trial |',
    '|---|---|---|---|---|---|---|',
    ...rows.map((r) => `| \`${r.kind}\` | ${r.role} | ${r.when} | ${r.does} | ${r.tests.length ? r.tests.map((t) => t.replace('tests/', '')).join(', ') : 'none'} | ${r.recorded.length ? r.recorded.map((x) => `${x.model} (${x.where})`).join('; ') : 'none'} | ${r.recorded[0]?.date ?? 'never'} |`),
    '',
  ]
  return lines.join('\n')
}

/**
 * The tokens of the latest recorded real reply of every kind (M10.21: the
 * guide price per hour of play in the settings), as a module the app ships
 * with: src/node/ai/measured.ts, made by npm run coverage.
 */
export function measuredModule(root: string): string {
  const dir = join(root, 'tests/fixtures/model')
  const rows: string[] = []
  if (existsSync(dir)) {
    for (const kind of readdirSync(dir).sort()) {
      const latest = readdirSync(join(dir, kind))
        .filter((f) => f.endsWith('.json'))
        .map((f) => JSON.parse(readFileSync(join(dir, kind, f), 'utf8')) as { date: string; model: string; usage?: { inputTokens: number; outputTokens: number } })
        .filter((r) => r.usage && r.usage.inputTokens > 0)
        .sort((a, b) => b.date.localeCompare(a.date))[0]
      if (latest?.usage) rows.push(`  ${kind}: { inputTokens: ${latest.usage.inputTokens}, outputTokens: ${latest.usage.outputTokens}, model: '${latest.model}', date: '${latest.date}' },`)
    }
  }
  return [
    '// Generated by npm run coverage from tests/fixtures/model: do not edit by hand.',
    '// The tokens of the latest real reply of each kind of call, for the guide price per hour (M10.21).',
    '',
    'export interface Measured {',
    '  inputTokens: number',
    '  outputTokens: number',
    '  model: string',
    '  date: string',
    '}',
    '',
    'export const MEASURED: Record<string, Measured> = {',
    ...rows,
    '}',
    '',
  ].join('\n')
}
