import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'
import { parse } from 'yaml'

// The inventory of fixed numbers (M10.20; Bram, 28 September 2026): every
// top-level numeric constant of the code, and where it belongs (docs/knobs.yaml):
// the content of a world, the settings of the app, or the code, with why.
// `npm run knobs` writes docs/KNOBS.md from it; tests/knobs.test.ts fails on a
// number without a place.

export const ROOTS = ['src/engine', 'src/node', 'src/main', 'src/chronicler']

export interface Constant {
  file: string
  line: number
  name: string
  value: string
}

export interface Place {
  place: 'world' | 'settings' | 'code' | 'unit'
  moved: boolean
  /** The knob's name to be (world), what it is (settings), or why it stays (code). */
  note: string
}

const CONSTANT = /^(?:export )?const ([A-Z][A-Z0-9_]*)(?:: [^=]+)? = (.+)$/

/** Every top-level constant whose value is a number, a sum of numbers, or a map of them. */
export function scan(root: string): Constant[] {
  const files: string[] = []
  const walk = (dir: string) => {
    for (const f of readdirSync(dir).sort()) {
      const p = join(dir, f)
      if (statSync(p).isDirectory()) walk(p)
      else if (f.endsWith('.ts')) files.push(p)
    }
  }
  for (const r of ROOTS) walk(join(root, r))
  const out: Constant[] = []
  for (const file of files) {
    readFileSync(file, 'utf8')
      .split('\n')
      .forEach((text, i) => {
        const m = CONSTANT.exec(text)
        if (!m) return
        const value = m[2]!.replace(/\s*\/\/.*$/, '').trim()
        if (!/^[\d(.-]|^\{\s*[a-z_]+:\s*[\d.]/.test(value) || !/\d/.test(value)) return
        out.push({ file: relative(root, file), line: i + 1, name: m[1]!, value })
      })
  }
  return out
}

/** The places of docs/knobs.yaml, by file and name; units by name alone. */
export function readPlaces(text: string): { units: Set<string>; places: Map<string, Place>; problems: string[] } {
  const raw = parse(text) as { units?: string[]; numbers?: Record<string, Record<string, string>> }
  const problems: string[] = []
  const places = new Map<string, Place>()
  for (const [file, names] of Object.entries(raw.numbers ?? {})) {
    for (const [name, said] of Object.entries(names ?? {})) {
      const m = /^(world|settings|code)( \(moved\))?: (.+)$/.exec(String(said))
      if (!m) {
        problems.push(`${file} ${name}: "${said}" is not "world: ...", "settings: ..." or "code: ..."`)
        continue
      }
      places.set(`${file} ${name}`, { place: m[1] as Place['place'], moved: Boolean(m[2]), note: m[3]! })
    }
  }
  return { units: new Set(raw.units ?? []), places, problems }
}

/** Every constant with its place; the constants without one, and the places no constant has any more. */
export function inventory(root: string, placesText: string): { rows: (Constant & Place)[]; unplaced: Constant[]; stale: string[]; problems: string[] } {
  const constants = scan(root)
  const { units, places, problems } = readPlaces(placesText)
  const rows: (Constant & Place)[] = []
  const unplaced: Constant[] = []
  const seen = new Set<string>()
  for (const c of constants) {
    if (units.has(c.name)) {
      rows.push({ ...c, place: 'unit', moved: false, note: 'a unit of time' })
      continue
    }
    const key = `${c.file} ${c.name}`
    seen.add(key)
    const place = places.get(key)
    if (place) rows.push({ ...c, ...place })
    else unplaced.push(c)
  }
  const stale = [...places.keys()].filter((k) => !seen.has(k))
  return { rows, unplaced, stale, problems }
}

const TITLES: Record<Exclude<Place['place'], 'unit'>, [string, string, string]> = {
  world: ['To the content of a world', 'Rules of play that may differ per world. They move to `world.yaml` or `rules.yaml`, with this value as the neutral default.', 'knob to be'],
  settings: ['To the settings of the app', 'How the app behaves. They move to the settings, with this value as the default.', 'what it is'],
  code: ['Stays in the code', 'Safety or technique: the reason is why it is no knob.', 'why'],
}

/** A knob of a world as the engine lists it (src/engine/knobs.ts). */
export interface KnobRow {
  id: string
  about: string
  unit: string
  default: number | Record<string, number>
  min: number
  max: number
  from: string
}

/** docs/KNOBS.md: the knobs of a world and of the app, then the numbers still in the code by place, and whether they have moved. */
export function knobsMarkdown(rows: (Constant & Place)[], knobs: KnobRow[] = [], appKnobs: Omit<KnobRow, 'from'>[] = []): string {
  const cell = (s: string) => s.replace(/\|/g, '\\|')
  const count = (place: Place['place']) => rows.filter((r) => r.place === place).length
  const lines = [
    '# The fixed numbers of the code',
    '',
    'Every top-level numeric constant in `src/engine`, `src/node`, `src/main` and `src/chronicler`, and where it belongs (M10.20). Generated by `npm run knobs` from the code and `docs/knobs.yaml`; do not edit by hand. A test fails when the code has a number that `docs/knobs.yaml` does not place.',
    '',
    `${knobs.length} rules of play are knobs of a world, and ${appKnobs.length} ways the app behaves are knobs of the app. Still in the code: ${rows.length} numbers, of which ${count('world')} are for the content of a world, ${count('settings')} for the settings of the app, ${count('code')} stay in the code, and ${count('unit')} are units of time; ${rows.filter((r) => r.moved).length} of them are only the default of something that has moved.`,
    '',
  ]
  if (knobs.length) {
    const shown = (v: number | Record<string, number>) => (typeof v === 'number' ? String(v) : Object.entries(v).map(([k, x]) => `${k} ${x}`).join(', '))
    lines.push(
      `## The knobs of a world (${knobs.length})`,
      '',
      'A world sets any of these in `world.yaml` under `knobs:`, by id: one number, or for a table only the rows that differ. The code reads them with `knob(world, id)` (src/engine/knobs.ts); a world that sets nothing plays by the defaults, which are the values the game had before. The editor shows them on the tab Knobs.',
      '',
      '| knob | what it does | unit | default | from, to | was in |',
      '| --- | --- | --- | --- | --- | --- |',
      ...knobs.map((k) => `| ${k.id} | ${cell(k.about)} | ${k.unit} | ${cell(shown(k.default))} | ${k.min} to ${k.max} | ${k.from} |`),
      '',
    )
  }
  if (appKnobs.length) {
    lines.push(
      `## The knobs of the app (${appKnobs.length})`,
      '',
      'How the app itself behaves. The player sets them under Settings, Advanced; they live in `knobs.json` in the app\'s own folder, written one key at a time (src/node/knobs.ts, the list in src/engine/appknobs.ts).',
      '',
      '| knob | what it does | unit | default | from, to |',
      '| --- | --- | --- | --- | --- |',
      ...appKnobs.map((k) => `| ${k.id} | ${cell(k.about)} | ${k.unit} | ${k.default} | ${k.min} to ${k.max} |`),
      '',
    )
  }
  for (const place of ['world', 'settings', 'code'] as const) {
    const [title, about, column] = TITLES[place]
    const these = rows.filter((r) => r.place === place)
    lines.push(`## ${title} (${these.length})`, '', about, '', `| number | where | value | ${column} | moved |`, '| --- | --- | --- | --- | --- |')
    // The file, not the line: the inventory changes when a number does, not when the code above it moves.
    for (const r of these) lines.push(`| ${r.name} | ${r.file} | \`${cell(r.value.length > 60 ? `${r.value.slice(0, 57)}...` : r.value)}\` | ${cell(r.note)} | ${r.moved ? 'yes' : ''} |`)
    lines.push('')
  }
  const units = rows.filter((r) => r.place === 'unit')
  lines.push(`## Units of time (${units.length})`, '', `The same everywhere, never a rule: ${[...new Set(units.map((u) => u.name))].join(', ')}.`, '')
  return `${lines.join('\n').trimEnd()}\n`
}
